name: #name of the exporter
url: #url including http/https of the CSV-based API to export, parts with <varName> are taken from additionalVariables: http://<varName> -> http://sample 
requireAuthentication: #true/false
authenticationMethod: #one of: bearer-token
pollingIntervalHours: #int
additionalVariables:
  varName: sample
  # Variables whose value only contains uppercase letters are taken from environment variables
  # FROM_THE_ENVIRONMENT must be the name of an environment variable inside the target exporter container
  envExample: FROM_THE_ENVIRONMENT